---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-persistentvolumeclaim-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-storageclass
  resources:
    requests:
      storage: 20Gi