---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persistentvolume-eks
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-storageclass
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02d445f402104bcad